#server:  
#  port: 8089  
#  session-timeout: 30  
#  context-path: /springboot
#  tomcat.max-threads: 100  
#  tomcat.uri-encoding: UTF-8 
# 
#spring:
#  datasource:
#    url : jdbc:mysql://localhost:3306/springboot?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#    username : root
#    password : root
#    driver-class-name : com.mysql.jdbc.Driver
#
#  freemarker:
#    checkTemplateLocation : false
#    cache: false
#    setting :
#      template_update_delay : 0
#      default_encoding : UTF-8
#
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      username: storeuser
#      password: 123456
#      database: jstore
#      authenticationDatabase: jstore
#---
#spring:
#    profiles: dev
#name: Dev
#
#---
#
## --spring.profiles.active=dev
#
#spring:
#    profiles: prd
#name: Prd